/**
 * Report Template Utilities
 * Functions to generate downloadable reports and certificates
 */

// Generate Retirement Certificate HTML
export const generateRetirementCertificate = (data: {
    certificateId: string;
    beneficiary: string;
    quantity: number;
    projectName: string;
    vintage: number;
    retirementDate: string;
    registry: string;
}) => {
    return `
<!DOCTYPE html>
<html>
<head>
    <title>Carbon Credit Retirement Certificate</title>
    <style>
        @page { size: A4 landscape; margin: 0; }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { 
            font-family: 'Georgia', serif; 
            background: linear-gradient(135deg, #f5f7fa 0%, #e4e8eb 100%);
            padding: 40px;
        }
        .certificate {
            background: white;
            border: 2px solid #2d5a27;
            border-radius: 10px;
            padding: 60px;
            max-width: 1000px;
            margin: 0 auto;
            position: relative;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }
        .certificate::before {
            content: '';
            position: absolute;
            top: 10px; left: 10px; right: 10px; bottom: 10px;
            border: 1px solid #2d5a27;
            border-radius: 6px;
        }
        .header { text-align: center; margin-bottom: 30px; }
        .logo { font-size: 28px; color: #2d5a27; font-weight: bold; letter-spacing: 2px; }
        .title { font-size: 36px; color: #1a3d16; margin: 20px 0; }
        .subtitle { color: #666; font-size: 14px; }
        .main-content { text-align: center; margin: 40px 0; }
        .quantity { font-size: 48px; color: #2d5a27; font-weight: bold; }
        .unit { font-size: 18px; color: #666; }
        .details { 
            display: grid; 
            grid-template-columns: 1fr 1fr; 
            gap: 20px; 
            margin: 40px 0;
            text-align: left;
        }
        .detail-item { padding: 15px; background: #f9faf9; border-radius: 8px; }
        .detail-label { font-size: 12px; color: #888; text-transform: uppercase; }
        .detail-value { font-size: 16px; color: #333; margin-top: 5px; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; }
        .cert-id { font-family: monospace; font-size: 12px; color: #888; }
        @media print { body { padding: 0; } }
    </style>
</head>
<body>
    <div class="certificate">
        <div class="header">
            <div class="logo">🌿 CREDO CARBON</div>
            <h1 class="title">Certificate of Carbon Credit Retirement</h1>
            <p class="subtitle">Verified Carbon Units Permanently Retired from Circulation</p>
        </div>
        
        <div class="main-content">
            <p class="quantity">${data.quantity.toLocaleString()}</p>
            <p class="unit">Metric Tonnes of CO₂ Equivalent (tCO₂e)</p>
        </div>
        
        <div class="details">
            <div class="detail-item">
                <p class="detail-label">Beneficiary</p>
                <p class="detail-value">${data.beneficiary}</p>
            </div>
            <div class="detail-item">
                <p class="detail-label">Project Name</p>
                <p class="detail-value">${data.projectName}</p>
            </div>
            <div class="detail-item">
                <p class="detail-label">Vintage Year</p>
                <p class="detail-value">${data.vintage}</p>
            </div>
            <div class="detail-item">
                <p class="detail-label">Registry</p>
                <p class="detail-value">${data.registry}</p>
            </div>
            <div class="detail-item">
                <p class="detail-label">Retirement Date</p>
                <p class="detail-value">${data.retirementDate}</p>
            </div>
            <div class="detail-item">
                <p class="detail-label">Certificate ID</p>
                <p class="detail-value">${data.certificateId}</p>
            </div>
        </div>
        
        <div class="footer">
            <p class="cert-id">This certificate is digitally generated by CredoCarbon Platform</p>
            <p class="cert-id">Verify at: https://credocarbon.com/verify/${data.certificateId}</p>
        </div>
    </div>
</body>
</html>`;
};

// Generate Issuance Certificate HTML
export const generateIssuanceCertificate = (data: {
    certificateId: string;
    projectName: string;
    quantity: number;
    vintage: number;
    serialStart: string;
    serialEnd: string;
    issuedDate: string;
    registry: string;
}) => {
    return `
<!DOCTYPE html>
<html>
<head>
    <title>Carbon Credit Issuance Certificate</title>
    <style>
        @page { size: A4 landscape; margin: 0; }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { 
            font-family: 'Georgia', serif; 
            background: linear-gradient(135deg, #e8f4f8 0%, #d0e8f2 100%);
            padding: 40px;
        }
        .certificate {
            background: white;
            border: 2px solid #1e5f74;
            border-radius: 10px;
            padding: 60px;
            max-width: 1000px;
            margin: 0 auto;
            position: relative;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }
        .certificate::before {
            content: '';
            position: absolute;
            top: 10px; left: 10px; right: 10px; bottom: 10px;
            border: 1px solid #1e5f74;
            border-radius: 6px;
        }
        .header { text-align: center; margin-bottom: 30px; }
        .logo { font-size: 28px; color: #1e5f74; font-weight: bold; letter-spacing: 2px; }
        .title { font-size: 36px; color: #133d4a; margin: 20px 0; }
        .subtitle { color: #666; font-size: 14px; }
        .main-content { text-align: center; margin: 40px 0; }
        .quantity { font-size: 48px; color: #1e5f74; font-weight: bold; }
        .unit { font-size: 18px; color: #666; }
        .project-name { font-size: 24px; color: #333; margin-top: 10px; }
        .serial-range {
            font-family: monospace;
            background: #f0f5f7;
            padding: 15px 30px;
            border-radius: 8px;
            display: inline-block;
            margin: 20px 0;
        }
        .details { 
            display: grid; 
            grid-template-columns: repeat(3, 1fr); 
            gap: 20px; 
            margin: 40px 0;
            text-align: left;
        }
        .detail-item { padding: 15px; background: #f9fafa; border-radius: 8px; }
        .detail-label { font-size: 12px; color: #888; text-transform: uppercase; }
        .detail-value { font-size: 16px; color: #333; margin-top: 5px; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; }
        .cert-id { font-family: monospace; font-size: 12px; color: #888; }
    </style>
</head>
<body>
    <div class="certificate">
        <div class="header">
            <div class="logo">🌿 CREDO CARBON</div>
            <h1 class="title">Carbon Credit Issuance Certificate</h1>
            <p class="subtitle">Official Record of Verified Carbon Units Issued</p>
        </div>
        
        <div class="main-content">
            <p class="quantity">${data.quantity.toLocaleString()}</p>
            <p class="unit">Verified Carbon Units (VCUs) Issued</p>
            <p class="project-name">${data.projectName}</p>
            <div class="serial-range">
                Serial Range: ${data.serialStart} — ${data.serialEnd}
            </div>
        </div>
        
        <div class="details">
            <div class="detail-item">
                <p class="detail-label">Vintage Year</p>
                <p class="detail-value">${data.vintage}</p>
            </div>
            <div class="detail-item">
                <p class="detail-label">Registry</p>
                <p class="detail-value">${data.registry}</p>
            </div>
            <div class="detail-item">
                <p class="detail-label">Issue Date</p>
                <p class="detail-value">${data.issuedDate}</p>
            </div>
        </div>
        
        <div class="footer">
            <p class="cert-id">Certificate ID: ${data.certificateId}</p>
            <p class="cert-id">Verify at: https://credocarbon.com/verify/${data.certificateId}</p>
        </div>
    </div>
</body>
</html>`;
};

// Download HTML as file
export const downloadHtmlAsFile = (html: string, filename: string) => {
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

// Print HTML certificate
export const printCertificate = (html: string) => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
        printWindow.onload = () => {
            printWindow.print();
        };
    }
};

// Generate and download retirement certificate
export const downloadRetirementCertificate = (data: Parameters<typeof generateRetirementCertificate>[0]) => {
    const html = generateRetirementCertificate(data);
    downloadHtmlAsFile(html, `retirement-certificate-${data.certificateId}.html`);
};

// Generate and download issuance certificate
export const downloadIssuanceCertificate = (data: Parameters<typeof generateIssuanceCertificate>[0]) => {
    const html = generateIssuanceCertificate(data);
    downloadHtmlAsFile(html, `issuance-certificate-${data.certificateId}.html`);
};
